import Dashboard from "@/components/Dashboard";
import React from "react";
import Head from "next/head";

const dashboard = () => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/2.png" />
      </Head>
      <div>
        <Dashboard />
      </div>
    </>
  );
};

export default dashboard;
