import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useState, useEffect } from "react";
import {
  Box,
} from "@chakra-ui/react";
import Login from "@/components/Login";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  return (
      <>
        <Head>
          <title>Starlight-Finance</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/2.png" />
        </Head>

        <Login />
        
      </>
    );
  }

