import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";
import {
  Center,
  FormControl,
  FormLabel,
  Spinner,
  Input,
  Button,
  Box,
} from "@chakra-ui/react";
import Login from "@/components/Login";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 10000);
  }, []);
  if (loading) {
    return (
      <>
        <Box
          fontSize="3rem"
          color="#FFFFFF"
          animation="fadeIn 2s"
          
        >
          Starlight Finance
        </Box>
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Login />
      </>
    );
  }
}
